### PR TITLE
Setup axios requests in client and server to fetch review list data

### PR DESCRIPTION
**Pull request by gabeyamartino**

### CODE REVIEW

**Review by rocknswimmer — COMMENTED** [review]
Looks pretty good. Only question is why comment out the whole useEffect? If you dont want a random product you can use the start variable to set product instead of random Id. Also might be helpful to mention this functionality in our read me.

**Comment by gabeyamartino** [comment]
Thanks Andy! Sorry, I commented the useEffect because on every render, I was getting the results for 37311, and then whichever randomly selected id on all of my get calls within Reviews. This made things hard to keep track of. So since the useEffect is responsible for the random number generator, it seemed okay to use just the initial product state of 37311 for now. Let me know what you think. 

Prior merge conflicts have been resolved. Some of them were just the difference of console.log vs. //console.log. I accepted Corinna's new server route handlers as well as her new formatting within her components. 

From here on out I will be waiting to talk with you guys before merging requests. It got a little hairy, but all of the info is there

Thanks! If all looks good to you, please feel free to merge

**Comment by rocknswimmer** [comment]
cool I think Corinna wrote the original useEffect. If you take a look at the one commented out there is an empty array argument at the end of the useEffect call. That limits the use effect to only run once on load rather than every time state changes. I think if you add that into the use effect you added to your component that would fix the issue.

**Comment by gabeyamartino** [comment]
> cool I think Corinna wrote the original useEffect. If you take a look at the one commented out there is an empty array argument at the end of the useEffect call. That limits the use effect to only run once on load rather than every time state changes. I think if you add that into the use effect you added to your component that would fix the issue.

Yeah that is right. The issue is that we set state to 37311 by default before use effect is called, so my useffect gets called on that, and then once the App useffect changes the state, mine is called again. Everytime I refresh I would see two use effect calls being logged for different products. It will be a super simple fix that we can look into when we reconvene!

**Comment by gabeyamartino** [comment]
So sorry Andy, you are 100% right. That's what I get for writing code at 10pm. I implemented my useEffect incorrectly. Thanks for catching that! Resubmitting now

**Comment by rocknswimmer** [comment]
watch the final decision live so looks good

**Comment by CorinnaCole** [comment]
Looks great. Thank you for all of this!

**Pull request merged**
